version: '3.8'

services:
  server:
    container_name: kanalys-server-dev
    build:
      context: .
      dockerfile: ./Dockerfile
    command: sh ./server.dev.sh
    ports:
      - 8000:8000
    volumes:
      - ./back/:/app/
      - ./server.dev.sh:/app/server.dev.sh
    env_file:
      - .env
    environment:
      - POSTGRES_USER=django
      - POSTGRES_DB=kanalys-dev-db
      - POSTGRES_PASSWORD=django
    depends_on:
      - database


  database:
    container_name: kanalys-db-dev
    image: postgres:15.1-alpine
    volumes:
      - kanalys-db-dev:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=django
      - POSTGRES_DB=kanalys-dev-db
      - POSTGRES_PASSWORD=django
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  kanalys-db-dev: